export const NOTIFICATION_TYPE = {
  DEBT_CREATED: "DEBT_CREATED",
  DEBT_CONFIRMED: "DEBT_CONFIRMED",
  DEBT_DISPUTED: "DEBT_DISPUTED",
  DEBT_SETTLED: "DEBT_SETTLED",
  DEBT_OVERDUE: "DEBT_OVERDUE",
  REPAYMENT_CREATED: "REPAYMENT_CREATED",
  REPAYMENT_CONFIRMED: "REPAYMENT_CONFIRMED",
  REPAYMENT_DISPUTED: "REPAYMENT_DISPUTED",
};

export const NOTIFICATION_REFERENCE_TYPE = {
  DEBT: "DEBT",
  REPAYMENT: "REPAYMENT",
};
